### ISSUE TITLE
Naming conventions not checked when Object type includes schema name

### ISSUE THREAD

**Issue by icams-wgka** [Trivadis/plsql-cop-validators#11]
Hello,

We are using PL/SQL Cop together with the custom validator which implements the naming conventions. When we declare a variable with a custom object type and include the schema name the naming conventions are not checked by PL/SQL Cop. 

E.g.
_DECLARE
   l_var NUMBER;
   invalid_var api_poc.custom_ot;
BEGIN
  ...
END;_

Although the variable _invalid_var_ is not according the naming conventions PL/SQL Cop is not reporting any problem. When we leave the schema name off the incorrect name is reported, but this is not an option for our project.

We noticed in the TrivadisGuideline3Plus class this is because of the _isQualifiedUdt_ check. When we leave this check out it is working as expected, but we are not sure about any side effects that may occur as there is a comment in the code that is saying:

_// reduce false positives, skip checking variables base on qualified UDTs_

It's not clear to us what this means.  How can we achieve a correct check on naming conventions, even if the schema name is included ?

**Comment by PhilippSalvisberg** [comment]
The scope of a check is a file. This validator expects all referenced objects to be be part of the file. 

This means when you reference an object type in an anonymous block the object type must be defined in the very same file. Something like this:

``` 
CREATE OR REPLACE TYPE custom_ot AS OBJECT (
	field1 INTEGER,
	field2 INTEGER
);
/

DECLARE
   l_var NUMBER;
   invalid_var custom_ot;
BEGIN
   NULL;
END;
/
```

In this case the validator knows that `custom_ot` is a object type and therefore it knows that it should be prefixed with an `o_`. 

But when you are referencing `api_poc.custom_ot` then the validator has no idea what this is. The else-case today is that it would assume that this must be a local variable and therefore be prefixed with a `l_`. This would be a false positive. We know that is not realistic to have all this DDLs defined in the same file. In fact this is most probably never the case. But since the validator scope is limited to a file we decided to live with false negatives and avoid false positives.

To solve the issue you can query the the Oracle Data Dictionary. In this case to get the type of `custom_ot` or the fully qualified `api_poc.custom_ot`.

You can do that in a custom validator, but you have to manage the DataSource yourself. This might change in one of the future releases of PL/SQL Cop (additional, optional parameters for the CLI, current connection in SQL Developer). But this has not yet been decided.

**Comment by icams-wgka** [comment]
Thanks for the clarification. 

Do you maybe have any suggestions how we could integrate a connection with the datasource from within the custom validator ? We have tried this by making a new JDBC connection and although this seems to work, it also seems to break our SQL Developer environment. 

I guess we have to make 2 versions of the validators.jar; one for the SQL Developer where we use the current SQL Developer connection and one for the command line (where we can use the JDBC connection) ? Any hints regarding this are welcome.

**Comment by PhilippSalvisberg** [comment]
I quite sure that it is should be be doable with a single validator and I do not see a reason why this should break the SQL Developer. 

However, supporting the creation of a JDBC based validator is beyond the scope of free support support we are able to give here.
