### ISSUE TITLE
OverrideTrivadisGuidelines to extend TrivadisGuidelines3Plus 

### ISSUE THREAD

**Issue by S-Koell** [Trivadis/plsql-cop-validators#14]
As shortly discussed in  [#10](https://github.com/Trivadis/plsql-cop-validators/issues/10#issuecomment-575095181):

I would like to use both the OverrideTrivadisGuidelines and the TrivadisGuidelines3Plus as a validator.
In order to do that the OverrideTrivadisGuidelines must extend the TrivadisGuidelines3Plus instead of the TrivadisGuidelines3 class.

**Comment by PhilippSalvisberg** [comment]
Oh yes, I forgot to thank you for the contribution of PR #12 . So, thanks a lot!

Regarding this request. The main intention of the validators in this repository is to show how to create them (not to provide validators ready to use, this is just a welcoming side-effect). 

To combine validators you can use inheritance. That's simple, but also limited. What I haven't shown yet is how you can combine multiple "independent" validators. For example

- SQLInjection
- OverrideTrivadisGuidelines 
- TrivadisGuidelines3Plus

Instead of TrivadisGuidelines3Plus which checks the Naming Conventions according the Trivadis Guidelines you may also want to use GLP or your own validator implementing your naming conventions.

This is possible. I'd think it would provide more value to show that. I could do that. In the end you should get your validator to be used in SQL Developer for free, but it will be implemented differently.

What do you think?

**Comment by S-Koell** [comment]
Was happy to contribute for #12 ! And thanks to you for adding it to a release so quickly 👍 

Regarding this topic:
If there is another way: Sure! As long as it archieves the same goal :)

**Comment by S-Koell** [comment]
Awesome! 🥇 
Will test it on Monday
