### ISSUE TITLE
Q: Do you plan to replace Xtend with Java?

### ISSUE THREAD

**Issue by deboiph** [Trivadis/plsql-cop-validators#21]
Dear Philipp,

I read in your "[Bye bye Xtend, Welcome Java](https://www.salvis.com/blog/2020/06/06/bye-bye-xtend-welcome-java/)" post that Xtend has been replaced with Java in the latest version of the utPLSQL extension for SQL Developer. Do you also intend to get rid of Xtend in the PLSQL Cop validators (in which case we will also have to migrate our custom validators)? Should it be the case, your post will help a lot. Thanks for having shared!

Best,
Philippe

**Comment by PhilippSalvisberg** [comment]
Thank you, Philipp.

We are currently planning to continue using Xtend for the time being. Mainly because the parser is written in Xtext and Xtext still uses Xtend behind the scenes, so we have the Xtend runtime libraries anyway.

We have also written a lot of tests in Xtend. Currently, switching to Java for parser-related projects is not very beneficial. It is different from the utPLSQL project.

But you can write your custom validators in Java or Xtend or both. So, you have the choice.

**Comment by deboiph** [comment]
Thanks for your reply.
